### ISSUE TITLE
MekkaBlue PreFlight Font

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/Lemonada-Arabic#5]
When I open https://github.com/Gue3bara/Lemonada-Arabic/blob/master/Lemonada-Arabic.glyphs and run the @mekkablue [Preflight Font](https://github.com/mekkablue/Glyphs-Scripts/blob/master/Test/Preflight%20Font.py) script, it lists many issues and then crashes at the end:

```
CHECKING FONT INFO AND INSTANCES ...

CHECKING FOR OPEN PATHS ...
- Glyph hehgoalHamzaabove-ar.fina, Layer Light Italic: 1 open path(s) found.
- Glyph hehgoalHamzaabove-ar.fina, Layer Bold Italic: 1 open path(s) found.
- Glyph tehMarbuta-ar.fina, Layer Bold Italic: 1 open path(s) found.

CHECKING FOR PATH DIRECTIONS ...
- Glyph sad-ar, Layer Light Italic: Bad path order or direction..
- Glyph sad-ar, Layer Bold Italic: Bad path order or direction..
- Glyph sad-ar.medi, Layer Light Italic: Bad path order or direction..
- Glyph sad-ar.medi, Layer Bold Italic: Bad path order or direction..
- Glyph sad-ar.init, Layer Light Italic: Bad path order or direction..
- Glyph sad-ar.init, Layer Bold Italic: Bad path order or direction..
- Glyph tah-ar, Layer Light Italic: Bad path order or direction..
- Glyph tah-ar, Layer Bold Italic: Bad path order or direction..
- Glyph meem-ar, Layer Light Italic: Bad path order or direction..
- Glyph meem-ar, Layer Bold Italic: Bad path order or direction..
- Glyph meem-ar.init, Layer Light Italic: Bad path order or direction..
- Glyph meem-ar.init, Layer Bold Italic: Bad path order or direction..
- Glyph heh-ar, Layer Light Italic: Bad path order or direction..
- Glyph heh-ar, Layer Bold Italic: Bad path order or direction..
- Glyph heh-ar.init, Layer Light Italic: Bad path order or direction..
- Glyph heh-ar.init, Layer Bold Italic: Bad path order or direction..
- Glyph hehgoalHamzaabove-ar.fina, Layer Light Italic: Bad path direction..
- Glyph hehgoalHamzaabove-ar.fina, Layer Bold Italic: Bad path direction..
- Glyph tehMarbuta-ar.fina, Layer Bold Italic: Bad path direction..
- Glyph zero, Layer Light Italic: Bad path order or direction..
- Glyph zero, Layer Bold Italic: Bad path order or direction..
- Glyph zero.numr, Layer Light Italic: Bad path order or direction..
- Glyph zero.numr, Layer Bold Italic: Bad path order or direction..
- Glyph ellipsis, Layer Light Italic: Bad path order or direction..
- Glyph ellipsis, Layer Bold Italic: Bad path order or direction..
- Glyph hyphen, Layer Light Italic: Bad path direction..
- Glyph hyphen, Layer Bold Italic: Bad path direction..
- Glyph currency, Layer Light Italic: Bad path order or direction..
- Glyph currency, Layer Bold Italic: Bad path order or direction..
- Glyph copyright, Layer Light Italic: Bad path order or direction..
- Glyph copyright, Layer Bold Italic: Bad path order or direction..
- Glyph registered, Layer Light Italic: Bad path order or direction..
- Glyph registered, Layer Bold Italic: Bad path order or direction..
- Glyph estimated, Layer Light Italic: Bad path order or direction..
- Glyph estimated, Layer Bold Italic: Bad path order or direction..
- Glyph dotaccentcomb, Layer Light Italic: Bad path direction..
- Glyph dotaccentcomb, Layer Bold Italic: Bad path direction..
- Glyph ringcomb, Layer Light Italic: Bad path order or direction..
- Glyph ringcomb, Layer Bold Italic: Bad path order or direction..
- Glyph tildecomb, Layer Light Italic: Bad path direction..
- Glyph tildecomb, Layer Bold Italic: Bad path direction..
- Glyph dotbelowcomb, Layer Light Italic: Bad path direction..
- Glyph dotbelowcomb, Layer Bold Italic: Bad path direction..

CHECKING FOR NODES OUT OF BOUNDS ...

CHECKING FOR ILLEGAL GLYPH NAMES ...

CHECKING FOR NAMING CONVENTION ...
Traceback (most recent call last):
  File "Preflight Font.py", line 215, in <module>
    checkStandardNames( Font )
  File "Preflight Font.py", line 184, in checkStandardNames
    calculatedNiceName = GSGlyphsInfo.niceGlyphNameForName_( legacyName )
TypeError: Expecting instance of GSGlyphsInfo as self, got one of unicode
End
```

**Comment by Gue3bara** [comment]
@davelab6 
<img width="549" alt="screenshot 2016-03-03 01 00 14" src="https://cloud.githubusercontent.com/assets/12478169/13478767/50ec2838-e0db-11e5-912c-704994712d91.png">
all is fixed but the problem with the naming convention, what exactly is wrong here?

**Comment by davelab6** [comment]
Its a bug that has arisen because Glyphs changed, see https://github.com/mekkablue/Glyphs-Scripts/issues/91
